syntax = "proto3";

message VideoSettings {
    uint32 horizontal = 1;
    uint32 vertical = 2;
    uint32 bitrate = 3; // in kbps
}

message AudioSettings {
    enum MicMix {
        Combine = 0;
        Duck = 1;
        Add = 2;
    }

    float gameVolume = 1;
    bool mic = 2;
    float micVolume = 3;
    float micThreshold = 4;
    MicMix micMix = 5;
}

message CameraSettings {
    message Position {
        enum CameraMode {
            Smooth = 0;
            ThirdPer = 1;
            FPFC = 2;
        }

        message Vector3 {
            float x = 1;
            float y = 2;
            float z = 3;
        }

        CameraMode cameraMode = 1;
        Vector3 position = 2;
        Vector3 rotation = 3;
        Vector3 offset = 4;
        Vector3 rotationOffset = 5;
        float smoothness = 6;
    }

    message Visibility {
        enum ShowMode {
            Normal = 0;
            Hidden = 1;
            // No cores for walls, no debris for notes
            Reduced = 2;
        }

        ShowMode notes = 1;
        ShowMode walls = 2;
        bool avatar = 3;
        bool ui = 4;
        bool cutParticles = 5;
    }

    Position position = 1;
    Visibility visibility = 2;
    float fps = 3;
    float fov = 4;
    bool orthographic = 5;
}

message VideoFrame {
    bytes data = 1;
    uint64 time = 2;
}

message AudioConfig {
    uint32 sampleRate = 1;
    uint32 channels = 2;
}

message AudioFrame {
    repeated float data = 1;
    uint64 time = 2;
}

message Input {
    float dx = 1;
    float dy = 2;
    bool mouseDown = 3;
    bool mouseUp = 4;
    float scroll = 5;
    repeated string keysDown = 6;
    repeated string keysUp = 7;
}

message PacketWrapper {
    oneof Packet {
        VideoSettings videoSettings = 1;
        AudioSettings audioSettings = 2;
        CameraSettings cameraSettings = 3;
        VideoFrame videoFrame = 4;
        AudioConfig audioConfig = 5;
        AudioFrame audioFrame = 6;
        Input input = 7;
    }
}
